name: remindly
description: A Flutter reminder app
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core functionality
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  intl: ^0.19.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  
  # UI
  flutter_slidable: ^3.0.0
  
  # WebView and HTTP Server
  webview_flutter: ^4.4.4
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  
  # File operations
  archive: ^3.4.10
  path_provider: ^2.1.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
  
  # App icon
  # To generate icons: flutter packages pub run flutter_launcher_icons:main
  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/icon/icon.png"